steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/isbn-2024i-418315/ntc-users-ms1', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/isbn-2024i-418315/ntc-users-ms1']
# Deploy container image to Cloud Run
#
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'ntc-users-ms1', '--image', 'gcr.io/isbn-2024i-418315/ntc-users-ms1', '--region', 'us-east4']
images:
- gcr.io/isbn-2024i-418315/ntc-users-ms1
#